ASV_counts_decontam <- read.table("ASV_counts_decontam.tsv", header=T, check.names = FALSE)
ASV_taxonomy_decontam <- read.delim("ASV_taxonomy_decontam.tsv", row.names=1, stringsAsFactors=TRUE)
metadata <- read_excel("all_metadata_01_22_2024.xlsm")
metadata_matching <- filter(metadata, metadata$Sampleid %in% colnames(ASV_counts_decontam))
metadata_matching <- column_to_rownames(metadata_matching, var = "Sampleid")
metadata_matching$Domcat <- factor(metadata_matching$Domcat, levels = c("wild", "free-ranging domestic","research","industrial"))
metadata_matching$treatment <- factor(metadata_matching$Treatment, levels = c("fecal", "control","challenged","abx_challenged"))

TREE <- read.tree("tree.nwk")
new.tree <- ape::multi2di(TREE)
ASV_counts_decontam_t <- t(ASV_counts_decontam)
ASV = otu_table(ASV_counts_decontam_t, taxa_are_rows = FALSE)
TAX = tax_table(as.matrix(ASV_taxonomy_decontam))
META = sample_data(metadata_matching)
CR_16S <- phyloseq(ASV, TAX, META, new.tree)

CR_16S_filt <- prune_samples(sample_sums(CR_16S) > 1000, CR_16S)
summarize_phyloseq(CR_16S_filt)
sd(sample_sums(CR_16S_filt))
CR_16S_clean <- prune_samples(sample_data(CR_16S_filt)$Treatment !="ABX", CR_16S_filt)
CR_16S_clean <- prune_samples(sample_data(CR_16S_clean)$Treatment !="N/A", CR_16S_clean)
CR_16S_clean <- prune_samples(sample_data(CR_16S_clean)$Domcat !="N/A", CR_16S_clean)
CR_16S_clean <- prune_samples(sample_data(CR_16S_clean)$Challenger !="N/A", CR_16S_clean)
CR_16S_clean <- prune_samples(sample_data(CR_16S_clean)$Individual !="N/A", CR_16S_clean)
